version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: health-app-db
    environment:
      MYSQL_ROOT_PASSWORD:     
      MYSQL_DATABASE: online_medicine             
      MYSQL_USER: root                 
      MYSQL_PASSWORD:          
    ports:
      - "3306:3306"  # Port 3306 untuk MySQL
    volumes:
      - db_data:/var/lib/mysql  # Volume untuk menyimpan data

volumes:
  db_data:
