# Ambil image dasar dari PHP dengan Apache
FROM php:7.4-apache

# Instal ekstensi PHP yang dibutuhkan
RUN docker-php-ext-install pdo_mysql mysqli

# Aktifkan modul Apache yang diperlukan
RUN a2enmod rewrite

# Set working directory
WORKDIR /var/www/html

# Salin kode sumber aplikasi ke dalam image
COPY . /var/www/html/

# Berikan hak akses yang sesuai
RUN chown -R www-data:www-data /var/www/html

# Expose port web server
EXPOSE 80